### ISSUE TITLE
Add LEDs for status of port Vio

### ISSUE THREAD

**Issue by electroniceel** [GlasgowEmbedded/Glasgow#127]
As discussed on IRC: it would be nice to have LEDs showing if Vio on each of the ports is enabled.

The LEDs should be next to the port connectors. Either on the side, where the J2 / J3 labels currently are, or on the inside, next to the "A" or "B" silkscreen labels (moving the testpoints or getting rid of them as we now have some on the back side).

I prefer the J2 / J3 label positions, because if you have an addon board connecting to both ports on top of Glasgow, you won't see them on the inside. But the exact positions of the J2 / J3 labels are near to the screw holes. So LEDs there could touch screw heads or washers. So maybe a few millimeters to the indside, where the R24 / R25 labels are now.

Regarding color: I'd prefer green, like a power led. Yellow like the activity led would also be an option.

I would connect them directly to the enable inputs of the voltage regulators as this signal has a constant voltage.

@marcan I can do a layout patch, but I guess you'll want to redo it afterwards because my try is not beautiful/symmetrical/... enough. So it is probably better if you do it.

**Comment by marcan** [comment]
Done in 104b364.
