### ISSUE TITLE
Reduce resistor part count

### ISSUE THREAD

**Issue by electroniceel** [GlasgowEmbedded/Glasgow#137]
Reduce the number of different resistors by replacing them with similar values. Less different resistor values reduces the count of reels needed for production, reducing costs.

Candidates:
R45 (33 ohms) to 47 ohms
or
R38, R39, R43 (47 ohms) to 33 ohms
These are used for the sync io and aux.

R3 (1 Meg) to 100k
This is decoupling of the usb shield. 1 Meg is a common value for that, but 100k should not make much of a difference.

**Comment by whitequark** [comment]
R38 needs to be 47 ohm to stay under AMR, so it is better to change R45.

Changing R3 to 100k is OK.

**Comment by electroniceel** [comment]
heartless cost cutters might also reduce the color variance of the leds. But I think that bit of indulgence is justified.

**Comment by whitequark** [comment]
Key part of the device! :D

**Comment by whitequark** [comment]
(You could cut the costs by making the brightness not matched as well before that, I think.)

**Comment by electroniceel** [comment]
the 6k8 R21 is just used for white. that could be changed to 4k7 or 10k

**Comment by whitequark** [comment]
I'd rather keep that one.

**Comment by electroniceel** [comment]
The other led resistor values seem to be used in some other circuits as well.

**Comment by marcan** [comment]
Yeah, it makes more sense to choose nicely matched resistors for the LEDs and then reuse those values where they fit (which is what I did a few times).
