### ISSUE TITLE
Better specify ATECC508A variant in schematic/bom

### ISSUE THREAD

**Issue by JJJollyjim** [GlasgowEmbedded/Glasgow#141]
The schematic and BOM only specify that the chip is a ATECC508A, which leaves open which of three packages, and two interfaces are used:

![Datasheet ordering information screenshot](https://user-images.githubusercontent.com/691552/57580510-9e6d7700-74fe-11e9-8e43-0546191de003.png)

It looks to me like the relevant variant is the ATECC508A-MAHDA: can someone confirm that?

**Comment by whitequark** [comment]
Yes, it is -MAHDA indeed.
