### ISSUE TITLE
Present revC1 on http://kicad-pcb.org

### ISSUE THREAD

**Issue by herostrat** [GlasgowEmbedded/glasgow#142]
Hey guys,

I wanted to thank you for this awesome project.
Just for the case you didn't know, there is a section on the official KiCad site were interesting projects are presented.
See: http://kicad-pcb.org/made-with-kicad/

I think this project is very interesting and would deserve a place on the list (although I am not qualified to make a decision on this). 
You can make a PR to include your board here: https://github.com/KiCad/kicad-website/tree/master/content/made-with-kicad

**Comment by attie** [comment]
This repo has since moved - https://gitlab.com/kicad/services/kicad-website/-/tree/master/content/made-with-kicad

Details on submitting a project are here: https://www.kicad.org/made-with-kicad/submit-a-project/

I think this would be a good thing to do! (probably starting with the CS hardware)

**Comment by whitequark** [comment]
@attie SGTM

**Comment by attie** [comment]
I'm planning to submit a generic "_Glasgow revC_" (rather than "_revCx_", if that works for you...

They require a `projectdeveloper` field - with your permission, I'll list you (wq)?

**Comment by whitequark** [comment]
Is that just one person? If so, `Catherine <whitequark@whitequark.org>`

**Comment by attie** [comment]
Seems to be, yes - no email, so is just "_Catherine_" okay?

**Comment by whitequark** [comment]
`Catherine 'whitequark'` maybe?

**Comment by whitequark** [comment]
@attie SGTM

**Comment by attie** [comment]
PR here: https://gitlab.com/kicad/services/kicad-website/-/merge_requests/594

**Comment by herostrat** [comment]
Thanks and awesome work
