### ISSUE TITLE
Spy-Bi-Wire support

### ISSUE THREAD

**Issue by smunaut** [GlasgowEmbedded/Glasgow#143]
Applet to support the 2 wire JTAG variant of TI for the msp430 along with a way to interact with the mspdebug tool (and/or gdb directly) would be really nice :)

http://www.ti.com/lit/ug/slau320ag/slau320ag.pdf

**Comment by whitequark** [comment]
I totally agree. Want to sponsor an MSP430 board for me? Although if they're cheap...
