### ISSUE TITLE
Silkscreen labels swapped on SCL and SDA testpoints

### ISSUE THREAD

**Issue by kevinmehall** [GlasgowEmbedded/glasgow#250]
Originally reported by `martinr` on Discord, confirmed in KiCad:

![image](https://user-images.githubusercontent.com/119951/103175623-8ad46880-4828-11eb-8e85-14575a7259e8.png)

**Comment by attie** [comment]
@esden - a candidate for revC3...

**Comment by electroniceel** [comment]
Fixed in wip-revC3-hardware branch
