### ISSUE TITLE
applet.interface.pulse_counter: new applet to count pulse events on pins

### ISSUE THREAD

**Issue by TomKeddie** [GlasgowEmbedded/glasgow#270]
I'm writing this applet for a testbench I'm building.  Initial version will just edge detect on pins and increment counters.
Other future features could include
- counter reset
- per pin configurable debounce time
- pulse width measurement (min/max/median/recent)

**Comment by attie** [comment]
see https://github.com/GlasgowEmbedded/glasgow/pull/218
