### ISSUE TITLE
applet.interface.analyzer - pullups look like they have been swapped in applet python

### ISSUE THREAD

**Issue by TomKeddie** [GlasgowEmbedded/glasgow#271]
ref https://github.com/GlasgowEmbedded/glasgow/blob/master/software/glasgow/applet/interface/analyzer/__init__.py#L85

If this is correct I suggest comment to explain what's going on.

```        
        if args.pull_ups:
            pull_low = set(args.pin_set_i)
        if args.pull_downs:
            pull_high = set(args.pin_set_i)
```

**Comment by whitequark** [comment]
That's a typo I believe. Would you be willing to send a PR?
