### ISSUE TITLE
revC2: incorrect part number for U2

### ISSUE THREAD

**Issue by festlv** [GlasgowEmbedded/glasgow#282]
[BOM](https://github.com/GlasgowEmbedded/glasgow/blob/99b81aac282f02ec3f3cda9566d929e30f1ecef4/hardware/boards/glasgow/revC2/bom.csv#L63) and [schematics](https://github.com/GlasgowEmbedded/glasgow/blob/99b81aac282f02ec3f3cda9566d929e30f1ecef4/hardware/boards/glasgow/glasgow.sch#L432) of revC2 have the following part number for U2: CAT24M01XI-T2

That part number corresponds to SOIC-8 package, however the footprint used on board is TSSOP-8.

The correct part number should be either:
CAT24M01YI−GT3 (-40..+85 deg C) **or** CAT24M01YE−GT3 (-40..+125 deg C)

**Comment by whitequark** [comment]
It should be CAT24M01YI−GT3.
