### ISSUE TITLE
Installing with Python 3.10

### ISSUE THREAD

**Issue by andresmanelli** [GlasgowEmbedded/glasgow#294]
Hello,

I tried installing the software from Python 3.10 and I had trouble with `aiohttp`. Apparently it's resolving to version 4.0.0, but version 3.8.1 is newer (See [this comment](https://github.com/aio-libs/aiohttp/issues/6898#issuecomment-1233074699)).

My workaround was to apply this patch:

```diff
diff --git a/software/setup.py b/software/setup.py
index 289ead7..0b7e0e1 100644
--- a/software/setup.py
+++ b/software/setup.py
@@ -29,7 +29,7 @@ setup(
         "amaranth",
         "fx2>=0.9",
         "libusb1>=1.8.1",
-        "aiohttp",
+        "aiohttp==3.8.3",
         "pyvcd",
         "bitarray",
         "crcmod",
```

Maybe this is a symptom for another problem, but this worked for me.

**Comment by whitequark** [comment]
Thanks, I'll take a look.

**Comment by whitequark** [comment]
Thanks for the report! Should be fixed now.
