### ISSUE TITLE
Replace `crcmod` with `crc`

### ISSUE THREAD

**Issue by whitequark** [GlasgowEmbedded/glasgow#309]
Crcmod is an ancient no longer updated package that doesn't upload wheels (and so requires pip to use deprecated setup.py based install method) and has a native dependency causing issues. We should replace it with [crc](https://github.com/Nicoretti/crc).

**Comment by bkerler** [comment]
Just had some spare time and thought you'd welcome some help :) 
Pushed PR #310 to port from crcmod to crc as requested.

**Comment by bkerler** [comment]
Cleaned up PR #310 and reissued new PR #311

**Comment by whitequark** [comment]
Fixed by #311.
