### ISSUE TITLE
Custom USB Manufacturer String

### ISSUE THREAD

**Issue by attie** [GlasgowEmbedded/glasgow#347]
Add mechanism to permit users to set a custom Manufacturer USB string when flashing the EEPROM (and add to firmware too?)

1BitSquared are producing Glasgow boards, and would like to be able to use the name `1bitsquared` (or similar).

cc @esden

**Comment by whitequark** [comment]
Yes it needs to be both in software (`glasgow factory`) and firmware.

The length I think is reasonable is 24 characters. We use 16 chars for serial but serials have higher entropy so they can be shorter.
