### ISSUE TITLE
Add host OS version to `--version` output

### ISSUE THREAD

**Issue by esden** [GlasgowEmbedded/glasgow#400]
We ask users to provide exact OS version when reporting bugs. It would be useful to have that info included in the `glasgow --version` output to make sure the information is provided correctly and with the necessary granularity.

Alternatively we could have a separate CLI option to provide all the necessary system information to make debugging of user reported bugs easier. As it might be good to know some extra information about how the hardware is connected to the system too.

**Comment by whitequark** [comment]
I have no idea how to actually implement this. Hopefully there is a library or something!

**Comment by whitequark** [comment]
Not sure it's so good on Debian...

**Comment by emaste** [comment]
Perhaps information from /etc/os-release? We adopted that from the Linux ecosystem, although I'm not sure if it's universal.

On my laptop it contains:
```
NAME=FreeBSD
VERSION=14.0-CURRENT
VERSION_ID=14.0
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 14.0-CURRENT"
CPE_NAME=cpe:/o:freebsd:freebsd:14.0
HOME_URL=https://FreeBSD.org/
BUG_REPORT_URL=https://bugs.FreeBSD.org/
```

**Comment by whitequark** [comment]
> Perhaps information from /etc/os-release? We adopted that from the Linux ecosystem, although I'm not sure if it's universal.

Yep, I think that's the way to go! `/etc/os-release` on *nix and its own thing on Windows.

**Comment by whitequark** [comment]
Also maybe we should add the versions of every installed package (or at least every `glasgow` dependency there) too; cf. https://github.com/GlasgowEmbedded/glasgow/issues/408, though there `--version` itself fails.
