### ISSUE TITLE
Implement MPSSE subtarget and FTDI emulation mode

### ISSUE THREAD

**Issue by whitequark** [GlasgowEmbedded/glasgow#49]
This is kind of annoying because it needs reenumeration logic in the firmware.

**Comment by marcan** [comment]
Don't forget to emulate the 32-bit EEPROM correctly to avoid being hit by FTDI's bricker :P

**Comment by whitequark** [comment]
Does anyone actually *want* this?

**Comment by esden** [comment]
MPSSE would be fairly useful. There is a bunch of software that uses MPSSE for "stuff" and it would be nice to just transparently use the Glasgow instead of an FTDI cable. Also that implementation might be a useful reference implementation for FTDI chip replacements.

**Comment by classic-gentleman** [comment]
> MPSSE would be fairly useful. There is a bunch of software that uses MPSSE for "stuff" and it would be nice to just transparently use the Glasgow instead of an FTDI cable. Also that implementation might be a useful reference implementation for FTDI chip replacements.

YES, for every point made.

**Comment by whitequark** [comment]
Ironically this was the original goal of the project and the very first committed gateware, but I don't think we even have the code left for it in-tree anymore.

**Comment by classic-gentleman** [comment]
https://github.com/usb-tools/Facedancer/blob/master/facedancer/devices/ftdi.py

Adapting this shouldn't be horrible...

**Comment by whitequark** [comment]
The problem is actually the firmware, and there is no great solution that I know of, especially for Windows.

**Comment by whitequark** [comment]
We decided not to do this. 60d09a217502f469682e3dd1c51c5e6bd2dfd586
