### ISSUE TITLE
Outdated board revision on kitspace.org revision

### ISSUE THREAD

**Issue by HerrSpace** [GlasgowEmbedded/glasgow#570]
I'm creating this issue mostly for documentation purposes.

The glasgow [board revision on kitspace.org](https://kitspace.org/boards/github.com/glasgowembedded/glasgow/glasgow_revc1/) was pinned to revC1 in https://github.com/kitspace/kitspace/commit/7e6a4e882c1e600e82bb83bc6850f153326841a2. This seems to have been in response to some branch shenanigans according to https://github.com/GlasgowEmbedded/glasgow/pull/199#issuecomment-678628235.

All of this seems no longer relevant as:
- the kitspace.yml in this repo was bumped to revC3 in https://github.com/GlasgowEmbedded/glasgow/commit/5c79669807fc1b9c051efd3a098c1ee4ca9346a7 by @whitequark
- [revC3 files are in the main branch](https://github.com/GlasgowEmbedded/glasgow/tree/main/hardware/boards/glasgow/revC3) now

So I propose reverting https://github.com/kitspace/kitspace/commit/7e6a4e882c1e600e82bb83bc6850f153326841a2 instead of re-pinning to revC3.

**Comment by whitequark** [comment]
LGTM
